# NumPy 用什么用？

大数据MapReduce(Hadoop等), GPU编程(CuPy, PyTorch, Tensorflow, 百度的PaddlePaddle, 华为的MindSpore, 旷视的忘了), 花钱的Matlab

知名的Python科学计算/数值计算扩展库， numpy,scipy,matplotlib---pandas算数据分析，scikit-learn是机器学习库。

4月份 试讲了一次， 半个小时重头戏都没讲到， 但幻灯片做都做了（改都改了）， 不如完成一下。



幻灯片改动自 黄海广​ 教授 中国海洋大学，  https://zhuanlan.zhihu.com/p/391261981

没有向他问授权， 但我也不打算直接讲PPT

这是哪？ 这是 jupyter notebook， 还讲啥PPT啊。


### 整体形式

当然不是全部留空， 比如练习时， 安装命令还要现打？ 当然不浪费这时间啦。

1份 完整版 notebook --- 我虽然说过很多次要脱稿， 但, 咳， 理想是美好的， 现实再说吧

1份 练习版 notebook

考虑到视频长度， 肯定分段

## 题外话

学习没那么容易（但也不一定“难于上青天”）

用 斯科特•扬 《如何高效学习》（Learn More, Study Less!）里 说的 （我也不查原文了）  知识点之间尽可能多建立联结， 有利于学习和掌握 —— 也许在纯教育学里 这完全不是什么新颖的观点， 但人家的事迹很有吸引力。

那 NumPy 这种 一般教学模式是什么样的呢？ 

1. 挑一些常用函数 
2. 逐个介绍， 并给一两个例子

由于数值计算， 例子全是数值， 建立的联结就是比较脆弱、孤立的。

也就是说， 对零基础入门来说， 枯燥了点、理解有限， 而有基础的可能只是想查个别情景下的使用


我希望 我这个能更强调具体使用场景（一两个）， 并且以 jupyter notebook的形式， 也更有利于 查询检索——虽然我的表达能力 可能影响会影响检索质量和效率。

所以， 我尝试以一个主线来串联， 建立多一点的联结

1. 使用场景（不一定有）
2. 失败场景（不一定有）
3. 代码例子
4. 相关函数的对比

也许好一点， 大概好得不多。

# 安装

In [2]:
!pip install ipython jupyterlab jupyter notebook 
!pip install numpy scipy matplotlib pandas torch

# https://developer.aliyun.com/article/652884
# -i https://pypi.tuna.tsinghua.edu.cn/simple 
# --trusted-host  mirrors.aliyun.com

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/


Looking in indexes: http://mirrors.aliyun.com/pypi/simple/


In [9]:
import numpy as np
import time

np.set_printoptions(precision=3)

## 预备

- Python          https://www.python.org/ 
- Miniconda https://conda.io/miniconda.html  
- 推荐这个 **Anaconda** www.anaconda.com/ 

**软件**

- VSCode            https://code.visualstudio.com/ 
- PyCharm Pro    https://www.jetbrains.com/pycharm/download


VS Code 带 jupytext, 应该好于 jupyterlab > jupyter notebook

比如目录功能， jupyter notebook 需要安装插件， 也挺麻烦的

另外， 我喜欢用 vim 的快捷键

另外， 除非电脑太卡了， 不然 NumPy的学习 不至于要用 Google Colab？

**虚拟环境**

创建虚拟环境 Virtual Environment


> virtualenv venv   
> source venv/bin/activate 

还是更推荐用 anaconda 创建——尤其是要安装 tensorflow-gpu时， 你需要找相应版本的 cudatoolkit和cudnn，

> conda create -n myenv python=3.9  
> conda activate myenv


# NumPy 是什么

NumPy(Numerical Python)是Python的一种开源的数值计算扩展库。 提供了两种基本对象：

1. ndarray：全称（n-dimensional array object）是储存单一数据类型的多维数组。
2. ufunc：全称（universal function object）它是一种能够对数组进行处理的函数。


## 为什么要用 NumPy

跟原生Python的对比

In [3]:
import numpy as np
import time

np.set_printoptions(precision=3)

In [2]:
n = 100
a1 = np.random.random(size = (100, 100))
a2 = np.random.random((100, 100))
a3 = np.zeros(shape = (100, 100))

NameError: name 'np' is not defined

In [7]:
# 原生python
# 偷懒了， 没用 list 列表

start = time.time()

for i in range(n):
    for j in range(n):
        for k in range(n):
            a3[i][j] += a1[i][k] * a2[k][j]
end = time.time()
print(end - start, 'second(s)')

0.887291431427002 second(s)


In [8]:
start = time.time()
a3_np = np.dot(a1, a2)
end = time.time()
print(end - start, 'second(s)')

0.0911872386932373 second(s)


In [10]:
a3_np - a3

array([[ 0.000e+00,  3.553e-15,  0.000e+00, ...,  0.000e+00,  0.000e+00,
         3.553e-15],
       [ 0.000e+00,  0.000e+00,  3.553e-15, ...,  0.000e+00,  0.000e+00,
         3.553e-15],
       [ 0.000e+00, -3.553e-15,  0.000e+00, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       ...,
       [ 0.000e+00,  0.000e+00,  0.000e+00, ..., -3.553e-15,  0.000e+00,
         0.000e+00],
       [ 0.000e+00,  0.000e+00, -3.553e-15, ..., -3.553e-15,  0.000e+00,
        -3.553e-15],
       [ 3.553e-15, -3.553e-15,  0.000e+00, ...,  0.000e+00,  0.000e+00,
        -3.553e-15]])

# 主线介绍

本文使用的例子如下图， 是一个3路softmax 分类任务的流程

![Softmax 3-分类](https://raw.githubusercontent.com/scilearner/NoWaste/master/image/3_class_demo.png)

为了简单， 对数据做一个简单假设， $X \in R^{n \times d}, z \in R^{d \times K}$, 其中 $n=300, d=5, K=3$,  大概如图

![Softmax 3-分类 数据](https://raw.githubusercontent.com/scilearner/NoWaste/master/image/3_gaussian.png)

In [12]:
# 为了得到一个分类预测、即走完流程图
# 需要哪些功能



# 大胆猜， 反正没检查


需要

1. 数据$X\in R^{n \times d}$——读取或生成创建
2. 模型参数$W\in R^{d \times K}$——生成创建
3. 数据通过模型（进行运算）$z = XW \in R^{n\times K}—— 矩阵乘法 
4. softmax里的 指数函数、求和 —— 涉及数轴和 **广播**
5. 交叉熵的计算 涉及到的内容 现在还说不清楚 —— **索引**与 **切片**

$X$ 和 $W$ 在 NumPy里 都是 用 ndarray对象表示

和 PyTorch 不一样，  PyTorch以 张量Tensor 为基础， 但模型参数默认有梯度， 和纯粹的数据是不太一样的


## 数组概念

N 维数组对象 ndarray (n-dimensional array object)

在不关注底层实现的情况下， 

所谓“用于存放同类型元素的多维数组”， 那是相对原生Python的列表、元组的优势， 而且仅限于 数值计算 领域。

- 比如， 根据 数组里具体的元素个数 和 元素类型， 可以直接得到该数组占的内存大小 —— C语言、JAVA语言都是这样
- 又比如， NumPy的数组对象 简化逻辑、 提高运算速度、不用写循环——就是封装的函数——更复杂的逻辑 该写循环还是要写循环的

这种“特点”， 属于 概念提炼， 属于一种总结、写作能力， 又需要相关背景。 自己总结不出来， 但看了总结，又觉得“无用”。


# NumPy 数组的创建

想要得到一个 ndarray 数组对象，方法：

1. 来自其他   
   图片、CSV、 原生Python的列表list/元组tuple、 PyTorch的张量、 Pandas、 多个ndarry数组
2. 创建数组


## 其他转换

In [ ]:
# 读图片的模块 有很多种——我的意思就是我不怎么看
# https://zhuanlan.zhihu.com/p/402833064

# CSV， 起码有两个， 一个python内置csv, 另一个pandas

# PyTorch
tensor_torch.detach().cpu().numpy()

In [4]:
# Python的列表或元组
# data = np.array( 列表或元组 )

list_1 = [1, 2, 3, 4]
tuple_1 = (5, 6, 7, 8)

array1 = np.array(list_1)
array2 = np.array(tuple_1)

type(array1), type(array2)

(numpy.ndarray, numpy.ndarray)

In [5]:

data1 = np.array([1, 2, 3]) # 创建一个一维数组

data2 = np.array([[1, 2, 3], [4, 5, 6]]) # 创建一个二维数组

data1, data2 

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [6]:
# 但反过来， ndarray转list可就

list(data1), list(data2)

([1, 2, 3], [array([1, 2, 3]), array([4, 5, 6])])

## 创建

为了创建/初始化一个数组对象， 我们需要一些信息：

1. 形状
2. 数值——全0、全1、随机（高斯、均匀）、序列
3. 类型——整数、浮点， 精度

数值内容为函数名， 形状与类型则为参数


## 数组的主要属性

个人觉得最常用的只有一个shape 形状/维度

其他的 一般不用， shape
- ndim 维度个数
- size 元素个数
- dtype 元素类型